export default function sheet1({
  buildDate,
  check,
  emergencyPlan,
  extintor,
  fireProtection,
  emergencyLight,
  emergencyRoute1,
  emergencyRoute2,
  emergencyRoute3,
  emergencyRoute4,
  other1,
  other2,
  other3,
  other4,
}: {
  buildDate: string
  check: string
  emergencyPlan: string
  extintor: string
  fireProtection: string
  emergencyLight: string
  emergencyRoute1: string
  emergencyRoute2: string
  emergencyRoute3: string
  emergencyRoute4: string
  other1: string
  other2: string
  other3: string
  other4: string
}) {
  return [
    [
      "1",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "AÑO CONSTRUCCIÓN",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "ANTES 2010",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "DATOS DE ENTRADA",
      "",
      "",
      "",
      "OBSERVACIONES",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "", //A
      "DESPUÉS 2010", //B
      "", //C
      "", //D
      "", //E
      "",
      "", //G
      "",
      "", //I
      "", //J
      "", //K
      "", //L
      "", //M
      "", //N
      "", //O
      "", //P
      "", //Q
      "", //R
      "", //S
      "", //T
      "AÑO CONSTRUCCIÓN", //U
      "", //V
      buildDate,
      "",
      '=IF(W4="ANTES 2010",IF(W5="SI",$D$9,$D$8),IF(W4="DESPUÉS 2010",IF(W5="SI",$F$9,$F$8),""))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "", //A
      "", //B
      "", //C
      "", //D
      "", //E
      "", //F
      "", //G
      "", //H
      "", //I
      "", //J
      "", //K
      "", //L
      "", //M
      "", //N
      "", //O
      "", //P
      "", //Q
      "", //R
      "", //S
      "", //T
      "CUMPLE", //U
      "", //V
      check, //W
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "PLAN DE EMERGENCIAS",
      "",
      emergencyPlan,
      "",
      '=IF(W6="NO TIENE",$D$12,IF(W6="TIENE DESACTUALIZADO",$D$13,""))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "CUMPLE",
      "",
      "ANTES 2010",
      "",
      "DESPUÉS 2010",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "EXTINTOR",
      "",
      extintor,
      "",
      '=IF(W7="","",IF(W7="NO TIENE",IF(W4="ANTES 2010",$D$17,IF(W4="DESPUÉS 2010",$F$17,"")),IF(W7="TIENE VENCIDO",$D$18,IF(W7="NO TIENE SUFICIENTES",$D$19,IF(W7="TIPO INADECUADO",$D$20,IF(W7="NO ESTÁ SEÑALIZADO",$D$21,IF(W7="ESTÁ MAL UBICADO",$D$22,IF(W7="MAL UBICADO Y SIN SEÑALIZAR",$D$23,""))))))))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "NO",
      "",
      "El establecimiento no cumple con los requerimientos de seguridad humana y sistemas de protección contra incendios, según lo establece acuerdo 20/95 y NSR/98, se recomienda:",
      "",
      "El establecimiento no cumple con los requerimientos de seguridad humana y sistemas de protección contra incendios, según lo establece NSR/10, se recomienda:",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "PORTECCIÓN CONTRA INCENDIOS",
      "",
      fireProtection,
      "",
      '=IF(AND(W4="ANTES 2010",W8="ALARMA"),$D$27,IF(AND(W4="DESPUÉS 2010",W8="ALARMA"),$F$27,IF(AND(W4="ANTES 2010",W8="TOMA FIJA"),$D$28,IF(AND(W4="DESPUÉS 2010",W8="TOMA FIJA"),$F$28,IF(AND(W4="ANTES 2010",W8="ROCIADORES"),$D$29,IF(AND(W4="DESPUÉS 2010",W8="ROCIADORES"),$F$29,IF(AND(W4="ANTES 2010",W8="TOMA FIJA Y ROCIADORES"),$D$30,IF(AND(W4="DESPUÉS 2010",W8="TOMA FIJA Y ROCIADORES"),$F$30,IF(AND(W4="ANTES 2010",W8="ALARMA Y ROCIADORES"),$D$31,IF(AND(W4="DESPUÉS 2010",W8="ALARMA Y ROCIADORES"),$F$31,IF(AND(W4="ANTES 2010",W8="ALARMA Y TOMA FIJA"),$D$32,IF(AND(W4="DESPUÉS 2010",W8="ALARMA Y TOMA FIJA"),$F$32,IF(AND(W4="ANTES 2010",W8="ALARMA, TOMA FIJA Y ROCIADORES"),$D$33,IF(AND(W4="DESPUÉS 2010",W8="ALARMA, TOMA FIJA Y ROCIADORES"),$F$33,""))))))))))))))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "SI",
      "",
      "El establecimiento cumple con los requerimientos de seguridad humana y sistemas de protección contra incendios, según lo establece acuerdo 20/95 y NSR/98, se recomienda:",
      "",
      "El establecimiento cumple con los requerimientos de seguridad humana y sistemas de protección contra incendios, según lo establece NSR/10, se recomienda:",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "ILUMINACIÓN DE EMERGENCIA",
      "",
      emergencyLight,
      "",
      '=IF(AND(W4="DESPUÉS 2010",W9="NO TIENE"),$F$37,IF(AND(W4="ANTES 2010",W9="NO TIENE"),$D$37,""))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "RUTAS DE EVACUACIÓN",
      "",
      emergencyRoute1,
      "",
      '=IF(W10="","",IF(W10="SEÑALIZAR RUTAS DE EVACUACIÓN",$D$41,IF(W10="PASAMANOS",$D$42,IF(W10="BORDES RIGIDOS / ANTIDESLIZANTES",$D$43,IF(AND(W10="MÍNIMO DE SALIDAS DE EMERGENCIA",$W$4="ANTES 2010"),$D$44,IF(AND(W10="MÍNIMO DE SALIDAS DE EMERGENCIA",$W$4="DESPUÉS 2010"),$F$44,""))))))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "PLAN DE EMERGENCIAS",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "RUTAS DE EVACUACIÓN",
      "",
      emergencyRoute2,
      "",
      '=IF(W11="","",IF(W11="SEÑALIZAR RUTAS DE EVACUACIÓN",$D$41,IF(W11="PASAMANOS",$D$42,IF(W11="BORDES RIGIDOS / ANTIDESLIZANTES",$D$43,IF(AND(W11="MÍNIMO DE SALIDAS DE EMERGENCIA",$W$4="ANTES 2010"),$D$44,IF(AND(W11="MÍNIMO DE SALIDAS DE EMERGENCIA",$W$4="DESPUÉS 2010"),$F$44,""))))))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "NO TIENE",
      "",
      "Implementar plan de emergencias según lo establece la Ley 1523 de 2012.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "RUTAS DE EVACUACIÓN",
      "",
      emergencyRoute3,
      "",
      '=IF(W12="","",IF(W12="SEÑALIZAR RUTAS DE EVACUACIÓN",$D$41,IF(W12="PASAMANOS",$D$42,IF(W12="BORDES RIGIDOS / ANTIDESLIZANTES",$D$43,IF(AND(W12="MÍNIMO DE SALIDAS DE EMERGENCIA",$W$4="ANTES 2010"),$D$44,IF(AND(W12="MÍNIMO DE SALIDAS DE EMERGENCIA",$W$4="DESPUÉS 2010"),$F$44,""))))))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "TIENE DESACTUALIZADO",
      "",
      "Mantener plan de emergencias actualizado según resolución 0312/2019.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "RUTAS DE EVACUACIÓN",
      "",
      emergencyRoute4,
      "",
      '=IF(W13="","",IF(W13="SEÑALIZAR RUTAS DE EVACUACIÓN",$D$41,IF(W13="PASAMANOS",$D$42,IF(W13="BORDES RIGIDOS / ANTIDESLIZANTES",$D$43,IF(AND(W13="MÍNIMO DE SALIDAS DE EMERGENCIA",$W$4="ANTES 2010"),$D$44,IF(AND(W13="MÍNIMO DE SALIDAS DE EMERGENCIA",$W$4="DESPUÉS 2010"),$F$44,""))))))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "OTROS",
      "",
      other1,
      "",
      '=IF(W14="MANTENIMIENTO ROCIADORES",$D$69,IF(W14="PRUEBAS PITOMÉTRICAS",$D$70,IF(W14="LIBRE DE HUMO",$D$71,IF(W14="RIESGO ELÉCTRICO",$D$72,IF(W14="ESCALERAS EN MADERA",IF(W4="ANTES 2010",$D$74,IF(W4="DESPUÉS 2010",$D$74,"")),IF(W14="UBICACIÓN DETECTORES HUMO",$D$73,""))))))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "OTROS",
      "",
      other2,
      "",
      '=IF(W15="MANTENIMIENTO ROCIADORES",$D$69,IF(W15="PRUEBAS PITOMÉTRICAS",$D$70,IF(W15="LIBRE DE HUMO",$D$71,IF(W15="RIESGO ELÉCTRICO",$D$72,IF(W15="ESCALERAS EN MADERA",IF(W5="ANTES 2010",$D$74,IF(W5="DESPUÉS 2010",$D$74,"")),IF(W15="UBICACIÓN DETECTORES HUMO",$D$73,""))))))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "EXTINTOR",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "OTROS",
      "",
      other3,
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "NO TIENE",
      "",
      "Implementar extintores conforme NSR98 y NTC 2885.",
      "",
      "Implementar extintores conforme NSR10 y NTC 2885.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "OTROS",
      "",
      other4,
      "",
      '=IF(W16="MANTENIMIENTO ROCIADORES",$D$69,IF(W16="PRUEBAS PITOMÉTRICAS",$D$70,IF(W16="LIBRE DE HUMO",$D$71,IF(W16="RIESGO ELÉCTRICO",$D$72,IF(W16="ESCALERAS EN MADERA",IF(W6="ANTES 2010",$D$74,IF(W6="DESPUÉS 2010",$D$74,"")),IF(W16="UBICACIÓN DETECTORES HUMO",$D$73,""))))))',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "TIENE VENCIDO",
      "",
      "Recargar o reemplazar extintor vencido conforme NTC 2885.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "NO TIENE SUFICIENTES",
      "",
      "Garantizar cantidad adecuada de extintores conforme NTC 2885.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      '=IF(Y4<>"",Y4,"")&IF(Y6<>"",CHAR(10)&Y6,"")&IF(Y7<>"",CHAR(10)&Y7,"")&IF(Y8<>"",CHAR(10)&Y8,"")&IF(Y9<>"",CHAR(10)&Y9,"")&IF(Y10<>"",CHAR(10)&Y10,"")&IF(Y11<>"",CHAR(10)&Y11,"")&IF(Y12<>"",CHAR(10)&Y12,"")&IF(Y13<>"",CHAR(10)&Y13,"")&IF(Y14<>"",CHAR(10)&Y14,"")&IF(Y15<>"",CHAR(10)&Y15,"")&IF(Y16<>"",CHAR(10)&Y16,"")&IF(Y17<>"",CHAR(10)&Y17,"")',
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "TIPO INADECUADO",
      "",
      "Implementar extintores del tipo adecuado para tipo de riesgo conforme NTC 2885.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "NO ESTÁ SEÑALIZADO",
      "",
      "Señalizar ubicación del extintor como se establece en NTC 1461.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "ESTÁ MAL UBICADO",
      "",
      "Ajustar la ubicación del extintor como se establece en NTC 2885.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "MAL UBICADO Y SIN SEÑALIZAR",
      "",
      "Ajustar la ubicación del extintor y señalizarlo como lo establecen la NTC 2885 y NTC 1461.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "PORTECCIÓN CONTRA INCENDIOS",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "ALARMA",
      "",
      "Implementar sistema de detección y alarma conforme al acuerdo 20/95.",
      "",
      "Implementar sistema de detección y alarma conforme a NSR10.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "TOMA FIJA",
      "",
      "Implementar sistema de tomas fijas de agua conforme al acuerdo 20/95.",
      "",
      "Implementar sistema de tomas fijas de agua conforme NSR10.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "ROCIADORES",
      "",
      "Implementar sistema de rociadores conforme al acuerdo 20/95.",
      "",
      "Implementar sistema de rociadores conforme NSR10.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "TOMA FIJA Y ROCIADORES",
      "",
      "Implementar sistema de tomas fijas de agua y rociadores automáticos conforme al acuerdo 20/95.",
      "",
      "Implementar sistema de tomas fijas de agua y rociadores automáticos conforme a NSR10.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "ALARMA Y ROCIADORES",
      "",
      "Implementar sistema de rociadores automáticos y detección y alarma conforme al acuerdo 20/95.",
      "",
      "Implementar sistema de rociadores automáticos y detección y alarma conforme a NSR10.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "ALARMA Y TOMA FIJA",
      "",
      "Implementar sistema de tomas fijas de agua y detección y alarma conforme al acuerdo 20/95.",
      "",
      "Implementar sistema de tomas fijas de agua y detección y alarma conforme a NSR10.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "ALARMA, TOMA FIJA Y ROCIADORES",
      "",
      "Implementar sistema de tomas fijas de agua, rociadores automáticos y detección y alarma conforme al acuerdo 20/95.",
      "",
      "Implementar sistema de tomas fijas de agua, rociadores automáticos y detección y alarma conforme a NSR10.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "ILUMINACIÓN DE EMERGENCIA",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "NO TIENE",
      "",
      "Implementar sistema de iluminación de emergencia conforme NSR/98.",
      "",
      "Implementar sistema de iluminación de emergencia conforme NSR/10.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "RUTAS DE EVACUACIÓN",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "SEÑALIZAR RUTAS DE EVACUACIÓN",
      "",
      "Señalizar salidas de emergencia y rutas de evacuación como lo establece la NTC 1461.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "PASAMANOS",
      "",
      "Instalar pasamanos en escaleras de salida de emergencia como lo establece la NTC 1700.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "BORDES RIGIDOS / ANTIDESLIZANTES",
      "",
      "Garantizar escaleras con bordes rigidos antideslizantes de acuerdo NTC1700.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "MÍNIMO DE SALIDAS DE EMERGENCIA",
      "",
      "Cumplir con el mínimo de salidas de emergencia como lo estipula NSR/98.",
      "",
      "Cumplir con el mínimo de salidas de emergencia como lo estipula NSR/10.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "RUTAS DE EVACUACIÓN",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "SEÑALIZAR RUTAS DE EVACUACIÓN",
      "",
      "Señalizar salidas de emergencia y rutas de evacuación como lo establece la NTC 1461.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "PASAMANOS",
      "",
      "Instalar pasamanos en escaleras de salida de emergencia como lo establece la NTC 1700.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "BORDES RIGIDOS / ANTIDESLIZANTES",
      "",
      "Garantizar escaleras con bordes rigidos antideslizantes de acuerdo NTC1700.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "MÍNIMO DE SALIDAS DE EMERGENCIA",
      "",
      "Cumplir con el mínimo de salidas de emergencia como lo estipula NSR/98.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "RUTAS DE EVACUACIÓN",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "SEÑALIZAR RUTAS DE EVACUACIÓN",
      "",
      "Señalizar salidas de emergencia y rutas de evacuación como lo establece la NTC 1461.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "PASAMANOS",
      "",
      "Instalar pasamanos en escaleras de salida de emergencia como lo establece la NTC 1700.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "BORDES RIGIDOS / ANTIDESLIZANTES",
      "",
      "Garantizar escaleras con bordes rigidos antideslizantes de acuerdo NTC1700.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "MÍNIMO DE SALIDAS DE EMERGENCIA",
      "",
      "Cumplir con el mínimo de salidas de emergencia como lo estipula NSR/98.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "RUTAS DE EVACUACIÓN",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "SEÑALIZAR RUTAS DE EVACUACIÓN",
      "",
      "Señalizar salidas de emergencia y rutas de evacuación como lo establece la NTC 1461.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "PASAMANOS",
      "",
      "Instalar pasamanos en escaleras de salida de emergencia como lo establece la NTC 1700.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "BORDES RIGIDOS / ANTIDESLIZANTES",
      "",
      "Garantizar escaleras con bordes rigidos antideslizantes de acuerdo NTC1700.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "MÍNIMO DE SALIDAS DE EMERGENCIA",
      "",
      "Cumplir con el mínimo de salidas de emergencia como lo estipula NSR/98.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "OTROS",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "MANTENIMIENTO ROCIADORES",
      "",
      "Realizar pruebas de funcionamiento de los rociadores y/o acta de funcionamiento conforme NFPA 72.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "PRUEBAS PITOMÉTRICAS",
      "",
      "Cumplir con los requisitos de inspección periódica, prueba y mantenimiento del sistema de protección contra incendios (pruebas pitométricas) conforme lo establece la NFPA25.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "LIBRE DE HUMO",
      "",
      "Implemetar señalización de espacio libre de humo conforme la Ley 1335/2009.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "RIESGO ELÉCTRICO",
      "",
      "Corregir cableado expuesto y/o en mal estado según lo establecido en el reglamento técnico de instalaciones eléctricas RETIE.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "UBICACIÓN DETECTORES HUMO",
      "",
      "Ajustar ubicación de los dectores de humo conforme NFPA 72.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    [
      "",
      "ESCALERAS EN MADERA",
      "",
      "Reemplazar escaleras de salida de emergencia en madera de acuerdo a lo que se establece en NSR/98",
      "",
      "Reemplazar escaleras de salida de emergencia en madera de acuerdo a lo que se establece en NSR/10",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
  ]
  //   return [
  //     [""], //1
  //     ["", "AÑO CONSTRUCCIÓN", ""], //2
  //     [
  //       "",
  //       "ANTES 2010",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "DATOS DE ENTRADA",
  //       "",
  //       "",
  //       "",
  //       "OBSERVACIONES",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ], //3
  //     [
  //       "", //A
  //       "DESPUÉS 2010", //B
  //       "", //C
  //       "", //D
  //       "", //E
  //       "", //F
  //       "", //G
  //       "", //H
  //       "", //I
  //       "", //J
  //       "", //K
  //       "", //L
  //       "", //M
  //       "", //N
  //       "", //O
  //       "", //P
  //       "", //Q
  //       "", //R
  //       "", //S
  //       "", //T
  //       "AÑO CONSTRUCCIÓN", //U
  //       "", //V
  //       buildDate, //W
  //       "",
  //       '=IF(W4="ANTES 2010";IF(W5="SI";D9;D8);IF(W4="DESPUÉS 2010";IF(W5="SI";F9;F8); ""))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ], //4
  //     [""], //5
  //     [""], //6
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "CUMPLE",
  //       check,
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ], //7
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "PLAN DE EMERGENCIAS",
  //       emergencyPlan,
  //       "",
  //       '=IF(W6="NO TIENE";D12;IF(W6="TIENE DESACTUALIZADO";D13;""))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "CUMPLE",
  //       "",
  //       "ANTES 2010",
  //       "",
  //       "DESPUÉS 2010",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "EXTINTOR",
  //       extintor,
  //       "",
  //       '=IF(W7="NO TIENE";IF(W4="ANTES 2010";D17;IF(W4="DESPUÉS 2010";F17;""));IF(W7="TIENE VENCIDO";D18;IF(W7="NO TIENE SUFICIENTES";D19;IF(W7="TIPO INADECUADO";D20;IF(W7="NO ESTÁ SEÑALIZADO";D21;IF(W7="ESTÁ MAL UBICADO";D22;IF(W7="MAL UBICADO Y SIN SEÑALIZAR";D23;"")))))))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "NO",
  //       "",
  //       "El establecimiento no cumple con los requerimientos de seguridad humana y sistemas de protección contra incendios, según lo establece acuerdo 20/95 y NSR/98, se recomienda:",
  //       "",
  //       "El establecimiento no cumple con los requerimientos de seguridad humana y sistemas de protección contra incendios, según lo establece NSR/10, se recomienda:",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "PORTECCIÓN CONTRA INCENDIOS",
  //       fireProtection,
  //       "",
  //       "",
  //       '=IF(AND(W4="ANTES 2010";W8="ALARMA");D27;IF(AND(W4="DESPUÉS 2010";W8="ALARMA");F27;IF(AND(W4="ANTES 2010";W8="TOMA FIJA");D28;IF(AND(W4="DESPUÉS 2010";W8="TOMA FIJA");F28;IF(AND(W4="ANTES 2010";W8="ROCIADORES");D29;IF(AND(W4="DESPUÉS 2010";W8="ROCIADORES");F29;IF(AND(W4="ANTES 2010";W8="TOMA FIJA Y ROCIADORES");D30;IF(AND(W4="DESPUÉS 2010";W8="TOMA FIJA Y ROCIADORES");F30;IF(AND(W4="ANTES 2010";W8="ALARMA Y ROCIADORES");D31;IF(AND(W4="DESPUÉS 2010";W8="ALARMA Y ROCIADORES");F31;IF(AND(W4="ANTES 2010";W8="ALARMA Y TOMA FIJA");D32;IF(AND(W4="DESPUÉS 2010";W8="ALARMA Y TOMA FIJA");F32;IF(AND(W4="ANTES 2010";W8="ALARMA, TOMA FIJA Y ROCIADORES");D33;IF(AND(W4="DESPUÉS 2010";W8="ALARMA, TOMA FIJA Y ROCIADORES");F33;""))))))))))))))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "SI",
  //       "",
  //       "El establecimiento cumple con los requerimientos de seguridad humana y sistemas de protección contra incendios, según lo establece acuerdo 20/95 y NSR/98, se recomienda:",
  //       "",
  //       "El establecimiento cumple con los requerimientos de seguridad humana y sistemas de protección contra incendios, según lo establece NSR/10, se recomienda:",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "ILUMINACIÓN DE EMERGENCIA",
  //       emergencyLight,
  //       "",
  //       "",
  //       '=IF(AND(W4="DESPUÉS 2010";W9="NO TIENE");F37;IF(AND(W4="ANTES 2010";W9="NO TIENE");D37;""))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "RUTAS DE EVACUACIÓN",
  //       emergencyRoute1,
  //       "",
  //       "",
  //       '=IF(W10="SEÑALIZAR RUTAS DE EVACUACIÓN";D41;IF(W10="PASAMANOS";D42;IF(W10="BORDES RIGIDOS / ANTIDESLIZANTES";D43;IF(AND(W10="MÍNIMO DE SALIDAS DE EMERGENCIA";W4="ANTES 2010");D44;IF(AND(W10="MÍNIMO DE SALIDAS DE EMERGENCIA";W4="DESPUÉS 2010");F44;"")))))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "PLAN DE EMERGENCIAS",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "RUTAS DE EVACUACIÓN",
  //       emergencyRoute2,
  //       "",
  //       "",
  //       '=IF(W11=""SEÑALIZAR RUTAS DE EVACUACIÓN"";D41;IF(W11=""PASAMANOS"";D42;IF(W11=""BORDES RIGIDOS / ANTIDESLIZANTES"";D43;IF(AND(W11=""MÍNIMO DE SALIDAS DE EMERGENCIA"";W4=""ANTES 2010"");D44;IF(AND(W11=""MÍNIMO DE SALIDAS DE EMERGENCIA"";W4=""DESPUÉS 2010"");F44;"""")))))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "NO TIENE",
  //       "",
  //       "Implementar plan de emergencias según lo establece la Ley 1523 de 2012.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "RUTAS DE EVACUACIÓN",
  //       emergencyRoute3,
  //       "",
  //       "",
  //       '=IF(W12=""SEÑALIZAR RUTAS DE EVACUACIÓN"";D41;IF(W12=""PASAMANOS"";D42;IF(W12=""BORDES RIGIDOS / ANTIDESLIZANTES"";D43;IF(AND(W12=""MÍNIMO DE SALIDAS DE EMERGENCIA"";W4=""ANTES 2010"");D44;IF(AND(W12=""MÍNIMO DE SALIDAS DE EMERGENCIA"";W4=""DESPUÉS 2010"");F44;"""")))))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "TIENE DESACTUALIZADO",
  //       "",
  //       "Mantener plan de emergencias actualizado según resolución 0312/2019.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "RUTAS DE EVACUACIÓN",
  //       emergencyRoute4,
  //       "",
  //       "",
  //       '=IF(W13=""SEÑALIZAR RUTAS DE EVACUACIÓN"";D41;IF(W13=""PASAMANOS"";D42;IF(W13=""BORDES RIGIDOS / ANTIDESLIZANTES"";D43;IF(AND(W13=""MÍNIMO DE SALIDAS DE EMERGENCIA"";W4=""ANTES 2010"");D44;IF(AND(W13=""MÍNIMO DE SALIDAS DE EMERGENCIA"";W4=""DESPUÉS 2010"");F44;"""")))))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "OTROS",
  //       other1,
  //       "",
  //       "",
  //       '=IF(W14="MANTENIMIENTO ROCIADORES";$D$69;IF(W14="PRUEBAS PITOMÉTRICAS";$D$70;IF(W14="LIBRE DE HUMO";$D$71;IF(W14="RIESGO ELÉCTRICO";$D$72;IF(W14="ESCALERAS EN MADERA";IF(W4="ANTES 2010";$D$74;IF(W4="DESPUÉS 2010";$D$74;""));IF(W14="UBICACIÓN DETECTORES HUMO";$D$73;""))))))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "OTROS",
  //       other2,
  //       "",
  //       "",
  //       '=IF(W15=""MANTENIMIENTO ROCIADORES"";D69;IF(W15=""PRUEBAS PITOMÉTRICAS"";D70;IF(W15=""LIBRE DE HUMO"";D71;IF(W15=""RIESGO ELÉCTRICO"";D72;IF(W15=""ESCALERAS EN MADERA"";IF(W4=""ANTES 2010"";D74;IF(W4=""DESPUÉS 2010"";F74;""""));IF(W15=""UBICACIÓN DETECTORES HUMO"";D73;""""))))))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "EXTINTOR",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "OTROS",
  //       other3,
  //       "",
  //       "",
  //       '=IF(W16=""MANTENIMIENTO ROCIADORES"";D69;IF(W16=""PRUEBAS PITOMÉTRICAS"";D70;IF(W16=""LIBRE DE HUMO"";D71;IF(W16=""RIESGO ELÉCTRICO"";D72;IF(W16=""ESCALERAS EN MADERA"";IF(W4=""ANTES 2010"";D74;IF(W4=""DESPUÉS 2010"";F74;""""));IF(W16=""UBICACIÓN DETECTORES HUMO"";D73;""""))))))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "NO TIENE",
  //       "",
  //       "Implementar extintores conformte NSR98 y NTC 2885.",
  //       "",
  //       "Implementar extintores conformte NSR10 y NTC 2885.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "OTROS",
  //       other4,
  //       "",
  //       "",
  //       '=IF(W17=""MANTENIMIENTO ROCIADORES"";D69;IF(W17=""PRUEBAS PITOMÉTRICAS"";D70;IF(W17=""LIBRE DE HUMO"";D71;IF(W17=""RIESGO ELÉCTRICO"";D72;IF(W17=""ESCALERAS EN MADERA"";IF(W4=""ANTES 2010"";D74;IF(W4=""DESPUÉS 2010"";F74;""""));IF(W17=""UBICACIÓN DETECTORES HUMO"";D73;""""))))))',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "TIENE VENCIDO",
  //       "",
  //       "Recargar o reemplazar extintor vencido conformte NTC 2885.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "NO TIENE SUFICIENTES",
  //       "",
  //       "Garantizar cantidad adecuada de extintores conformte NTC 2885.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       '=IF(Y4<>"""";Y4;"""")&IF(Y6<>"""";CHAR(10)&Y6;"""")&IF(Y7<>"""";CHAR(10)&Y7;"""")&IF(Y8<>"""";CHAR(10)&Y8;"""")&IF(Y9<>"""";CHAR(10)&Y9;"""")&IF(Y10<>"""";CHAR(10)&Y10;"""")&IF(Y11<>"""";CHAR(10)&Y11;"""")&IF(Y12<>"""";CHAR(10)&Y12;"""")&IF(Y13<>"""";CHAR(10)&Y13;"""")&IF(Y14<>"""";CHAR(10)&Y14;"""")&IF(Y15<>"""";CHAR(10)&Y15;"""")&IF(Y16<>"""";CHAR(10)&Y16;"""")&IF(Y17<>"""";CHAR(10)&Y17;"""")',
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "TIPO INADECUADO",
  //       "",
  //       "Implementar extintores del tipo adecuado para tipo de riesgo conforme NTC 2885.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "NO ESTÁ SEÑALIZADO",
  //       "",
  //       "Señalizar ubicación del extintor como se establece en NTC 1461.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "ESTÁ MAL UBICADO",
  //       "",
  //       "Ajustar la ubicación del extintor como se establece en NTC 2885.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "MAL UBICADO Y SIN SEÑALIZAR",
  //       "",
  //       "Ajustar la ubicación del extintor y  señalizarlo como lo establecen la NTC 2885 y NTC 1461.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "PORTECCIÓN CONTRA INCENDIOS",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "ALARMA",
  //       "",
  //       "Implementar sistema de detección y alarma conforme al acuerdo 20/95.",
  //       "",
  //       "Implementar sistema de detección y alarma conforme a NSR10.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "TOMA FIJA",
  //       "",
  //       "Implementar sistema de tomas fijas de agua conforme al acuerdo 20/95.",
  //       "",
  //       "Implementar sistema de tomas fijas de agua conforme NSR10.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "ROCIADORES",
  //       "",
  //       "Implementar sistema de rociadores conforme al acuerdo 20/95.",
  //       "",
  //       "Implementar sistema de rociadores conforme  NSR10.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "TOMA FIJA Y ROCIADORES",
  //       "",
  //       "Implementar sistema de tomas fijas de agua y rociadores automáticos conforme al acuerdo 20/95.",
  //       "",
  //       "Implementar sistema de tomas fijas de agua y rociadores automáticos conforme a NSR10.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "ALARMA Y ROCIADORES",
  //       "",
  //       "Implementar sistema de rociadores automáticos y detección y alarma conforme al acuerdo 20/95.",
  //       "",
  //       "Implementar sistema de rociadores automáticos y detección y alarma conforme a NSR10.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "ALARMA Y TOMA FIJA",
  //       "",
  //       "Implementar sistema de tomas fijas de agua y detección y alarma conforme al acuerdo 20/95.",
  //       "",
  //       "Implementar sistema de tomas fijas de agua y detección y alarma conforme a NSR10.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "ALARMA, TOMA FIJA Y ROCIADORES",
  //       "",
  //       "Implementar sistema de tomas fijas de agua, rociadores automáticos y detección y alarma conforme al acuerdo 20/95.",
  //       "",
  //       "Implementar sistema de tomas fijas de agua, rociadores automáticos y detección y alarma conforme a NSR10.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "ILUMINACIÓN DE EMERGENCIA",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "NO TIENE",
  //       "",
  //       "Implementar sistema de iluminación de emergencia conforme NSR/98.",
  //       "",
  //       "Implementar sistema de iluminación de emergencia conforme NSR/10.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "RUTAS DE EVACUACIÓN",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "SEÑALIZAR RUTAS DE EVACUACIÓN",
  //       "",
  //       "Señalizar salidas de emergencia y rutas de evacuación como lo establece la NTC 1461.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "PASAMANOS",
  //       "",
  //       "Instalar pasamanos en escaleras de salida de emergencia como lo establece la NTC 1700.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "BORDES RIGIDOS / ANTIDESLIZANTES",
  //       "",
  //       "Garantizar escaleras con bordes rigidos antideslizantes de acuerdo NTC1700.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "MÍNIMO DE SALIDAS DE EMERGENCIA",
  //       "",
  //       "Cumplir con el mínimo de salidas de emergencia como lo estipula NSR/98.",
  //       "",
  //       "Cumplir con el mínimo de salidas de emergencia como lo estipula NSR/10.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "RUTAS DE EVACUACIÓN",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "SEÑALIZAR RUTAS DE EVACUACIÓN",
  //       "",
  //       "Señalizar salidas de emergencia y rutas de evacuación como lo establece la NTC 1461.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "PASAMANOS",
  //       "",
  //       "Instalar pasamanos en escaleras de salida de emergencia como lo establece la NTC 1700.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "BORDES RIGIDOS / ANTIDESLIZANTES",
  //       "",
  //       "Garantizar escaleras con bordes rigidos antideslizantes de acuerdo NTC1700.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "MÍNIMO DE SALIDAS DE EMERGENCIA",
  //       "",
  //       "Cumplir con el mínimo de salidas de emergencia como lo estipula NSR/98.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "RUTAS DE EVACUACIÓN",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "SEÑALIZAR RUTAS DE EVACUACIÓN",
  //       "",
  //       "Señalizar salidas de emergencia y rutas de evacuación como lo establece la NTC 1461.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "PASAMANOS",
  //       "",
  //       "Instalar pasamanos en escaleras de salida de emergencia como lo establece la NTC 1700.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "BORDES RIGIDOS / ANTIDESLIZANTES",
  //       "",
  //       "Garantizar escaleras con bordes rigidos antideslizantes de acuerdo NTC1700.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "MÍNIMO DE SALIDAS DE EMERGENCIA",
  //       "",
  //       "Cumplir con el mínimo de salidas de emergencia como lo estipula NSR/98.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "RUTAS DE EVACUACIÓN",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "SEÑALIZAR RUTAS DE EVACUACIÓN",
  //       "",
  //       "Señalizar salidas de emergencia y rutas de evacuación como lo establece la NTC 1461.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "PASAMANOS",
  //       "",
  //       "Instalar pasamanos en escaleras de salida de emergencia como lo establece la NTC 1700.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "BORDES RIGIDOS / ANTIDESLIZANTES",
  //       "",
  //       "Garantizar escaleras con bordes rigidos antideslizantes de acuerdo NTC1700.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "MÍNIMO DE SALIDAS DE EMERGENCIA",
  //       "",
  //       "Cumplir con el mínimo de salidas de emergencia como lo estipula NSR/98.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "OTROS",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "MANTENIMIENTO ROCIADORES",
  //       "",
  //       "Realizar pruebas de funcionamiento de los rociadores y/o acta de funcionamiento conforme NFPA 72.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "PRUEBAS PITOMÉTRICAS",
  //       "",
  //       "Cumplir con los requisitos de inspección periódica, prueba y mantenimiento del sistema de protección contra incendios (pruebas pitométricas) conforme lo establece la NFPA25.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "LIBRE DE HUMO",
  //       "",
  //       "Implemetar señalización de espacio libre de humo conforme la Ley 1335/2009.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "RIESGO ELÉCTRICO",
  //       "",
  //       "Corregir cableado expuesto y/o en mal estado según lo establecido en el reglamento técnico de instalaciones eléctricas RETIE.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "UBICACIÓN DETECTORES HUMO",
  //       "",
  //       "Ajustar ubicación de los dectores de humo conforme NFPA 72.",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //     [
  //       "",
  //       "ESCALERAS EN MADERA",
  //       "",
  //       "Reemplazar escaleras de salida de emergencia en madera de acuerdo a lo que se establece en NSR/98",
  //       "",
  //       "Reemplazar escaleras de salida de emergencia en madera de acuerdo a lo que se establece en NSR/10",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //       "",
  //     ],
  //   ]
}
